FROM serve-project-base

WORKDIR /app
ENV PYTHONPATH=/app

COPY train_pipeline/model.py .
COPY inference_server/*.py .
EXPOSE 5000

CMD ["fastapi", "run", "app.py", "--host", "0.0.0.0", "--port", "8080"]